### PR TITLE
Attempt at fixing the issue.

### PR DESCRIPTION
**Pull request by etisdew**
I'm not completely clear why you disable hardware acceleration but this has been working for me. Hopefully this can get you through your roadblock.

https://github.com/singuerinc/overlay/issues/29

### CODE REVIEW

**Comment by singuerinc** [comment]
Hi @etisdew thanks for the PR, unfortunately it does not correct the issue. It's still impossible to click through the transparent area when the application is in front.
I disabled the hardware acceleration in a attempt to fix the problem, but it doesn't work with or without.

Maybe it's easier to understand in this video:
https://www.dropbox.com/s/hzwv7k2gvndcypx/movie.mp4?dl=0

I suppose that the only way to fix it is to migrate the app to NW.js as suggested by @GnorTech in #29  but I don't know how much work could be since I didn't have the time to look at their project.

There isn't too much code specific for Electron (I think just upload of the image and the auto-update), the rest is just a React app, so it should be possible to copy/paste the code to NW.js if it works in the same way.

I need to check Electron 3... looks like the `SetIgnoreMouseEvents` works on Mac too https://github.com/electron/electron/pull/12281

**Comment by etisdew** [comment]
Ahh I see, a notable difference with my method of focusing a window is a reliance on alt + tab to refocus my windows. I wish you all luck, you might have more support on the ms side of things and 3.0 has been great so far. Hope it might offer you what you need.

**Comment by andens** [comment]
I assume your application covers the entire screen and you want the regions outside the yellow tint to be click-through. This is very similar to the use case I originally implemented mouse forward for; it's just an inverted area but the same idea nonetheless.

The Electron developers seem to have been very busy. My implementation was accepted into master a while ago, but it's now included in its entirety in the 3-0-x branch, which is nice to see. Spontaneously I would like to say yes to your question. Just remember that Linux has no implementation of mouse forward. If you can, please try [this example](https://github.com/andens/electron-mouse-forward-example) with Electron 3. I would love to hear if the Mac implementation works properly. It was a while ago that I touched it, so just poke me if you have any questions. Read on if you want to hear some background mumbo jumbo about the forwarding feature.

---

`SetIgnoreMouseEvents` has been available for all supported OSs in its "base form" for some time, and the naïve approach for me was to simply start ignoring mouse events when I entered an element, and accept them again when I left it. This caused quite bad flickering, but that was not the real problem.

The problem is that when you start ignoring mouse events, Chromium no longer gets informed about them. This means that it does not have the necessary information to determine Javascript mouse events, as they in turn depend on OS mouse events, which also meant that I couldn't reset the state the way I wanted.

What mouse forwarding does is that it snoops the mouse move events and passes them along to Chromium. This way we are essentially saying "Here, these are the mouse move events that happened. We are definitely not routing them anywhere else", and Chromium goes on its merry way. This allows Chromium to fire useful events because all of a sudden it has the necessary information to do so, despite us ignoring mouse events in general. Now it's just a matter of using them creatively.

Of course, this is not a cure all remedy. It doesn't even bother with transparency, but you can enable/disable ignoring as the mouse crosses element borders (which is, from what I can tell, what you need). The benefit of this approach is that you can operate on a per element basis. Some translucent elements could ignore whereas some do not; they do not have to be completely transparent or ignore based on their background exclusively. However, per pixel transparency is not directly supported. I guess you could get a sample on mouse moves and use that to determine whether to enable/disable. I did read a little about this for the Windows API, but I'm afraid that it's very iffy down on the OS level.

**Comment by singuerinc** [comment]
@andens wow! I clone the repo you told me and it worked!
I updated my app with that technique and it's working!
Thanks a lot to everyone, finally this app works as expected and it's useful! cc @etisdew

**Pull request closed without merging**
